dist: trusty
language: perl
perl:
  - "5.14"
sudo: false
install:
  - cpanm --force Getopt::Long Test::Most Net::SCP Git::Repository YAML::XS Time::Mock File::Slurp Date::Parse 
script:
  - make test
