general:
  repository:
    url: 'git+ssh://git.internal.sanger.ac.uk/repos/git/pathogens/general.git'
    branch: 'farm3'
  directories_to_build: ['java','perl','python','shell','c','splimer','r']

checkout_directory: "/tmp"

directories:
  production_bin:    '/software/pathogen/internal/prod/bin'
  production_lib:    '/software/pathogen/internal/prod/lib'
  pathdev_lib:       '/software/pathogen/internal/pathdev/lib'
  pathdev_bin:       '/software/pathogen/internal/pathdev/bin'  
  preproduction_bin: '/software/pathogen/internal/preprod/bin'
  preproduction_lib: '/software/pathogen/internal/preprod/lib'
  production_java:   '/software/pathogen/internal/pathdev/java'
  production_etc:    '/software/pathogen/etc'
  documentation:     '/nfs/WWWdev/INTWEB_docs/htdocs/Teams/Team81/docs'

application_locations:
  perl:           '/software/bin/perl'
  natural_docs:   '/software/pathogen/external/apps/usr/local/NaturalDocs-1.52/NaturalDocs'
  source_control: '/usr/bin/git'
  make:           '/usr/bin/make'
deployment:
  server: 'pathpipe-farm3'
  user: 'pathdb'
