general:
  python: [
            ['scripts/bam2cov',                         'production_bin'],
            ['scripts/bam2snp',                         'production_bin'],
            ['scripts/crawler.py',                      'production_bin'],
            ['scripts/features_with_term_property.py',  'production_bin'],
            ['scripts/get_orthologues_filtered.py',     'production_bin'],
            ['scripts/get_synonyms.py',                 'production_bin'],
            ['scripts/gffmini.py',                      'production_bin'],
            ['scripts/run_with_json.py',                'production_bin'],
            ['scripts/wiki_extract.py',                 'production_bin'],
            ['scripts/wiki_load_homepages.py',          'production_bin'],
            ['scripts/writedb_entries.py',              'production_bin'],
            ['scripts/fastn2gc.py',                     'production_bin'],
            ['scripts/mh12_utils.py',                   'production_bin'],
            ['scripts/fastn.py',    	                  'production_bin'],
            ['scripts/fastn_split.py',                	'production_bin'],
        ]
  
  perl: [
            ['scripts/fastq_to_fasta',                'production_bin'],
            ['scripts/merge_rnaseq_expression_spreadsheets.pl', 'pathdev_bin'],
            ['scripts/convert_gff3_to_gff2.pl',       'production_bin'],
            ['scripts/tradis_merge_plots',            'production_bin'],
            ['scripts/validate_multi_fasta_alignment','production_bin'],
            ['scripts/tradis_gene_insert_sites',      'production_bin'],
            ['scripts/backup_documents.pl',           'pathdev_bin'   ], 
            ['scripts/populate_organisms.pl',         'pathdev_bin'   ],
            ['scripts/rt_report',                     'pathdev_bin'   ],
            ['scripts/update_lustre_ref_genomes.pl',  'pathdev_bin'   ],
            ['scripts/check_lustre.pl',               'pathdev_bin'   ],
            ['scripts/fetch_references.pl',           'pathdev_bin'   ],
            ['scripts/list_used_references.pl',       'pathdev_bin'   ],
            ['scripts/reads_analysis.pl',             'pathdev_bin'   ],
            ['scripts/scaffolder',                    'pathdev_bin'   ],
            ['scripts/set_orgprops.pl',               'pathdev_bin'   ],    
            ['scripts/check_aux_files.pl',            'pathdev_bin'   ],  
            ['scripts/num_lanes_in_pipelines',        'pathdev_bin'   ],
            ['scripts/forecast_sequencing_data.pl',   'pathdev_bin'   ],
            ['scripts/ena_submissions_update.pl',     'pathdev_bin'   ],
            ['scripts/generate_project_pages.pl',     'pathdev_bin'   ],
            ['scripts/retry_failed_lanes.pl',         'pathdev_bin'   ],
            ['scripts/update_species_table.pl',       'pathdev_bin'   ],
            ['scripts/scaffold_perl_application.pl',  'pathdev_bin'   ],
            ['scripts/reffind',                       'production_bin'],
            ['scripts/whereismydata',                 'production_bin'],
            ['scripts/pathfind',                      'production_bin'],
            ['scripts/annotationfind',                'production_bin'],
            ['scripts/plexfind',                      'production_bin'],
            ['scripts/mapfind',                       'production_bin'],
            ['scripts/snpfind',                       'production_bin'],
            ['scripts/rnaseqfind',                    'production_bin'],
            ['scripts/assemblyfind',                  'production_bin'],
            ['scripts/rnaexp2dnaplotter',             'production_bin'],
            ['scripts/accessionfind',                 'production_bin'],
            ['scripts/bigger_blast.pl',               'production_bin'],
            ['scripts/flexi_blast.pl',                'production_bin'],
            ['scripts/fasta_chunker.pl',              'production_bin'],
            ['scripts/blast_formatter.pl',            'production_bin'],
            ['scripts/rfam_scan.pl',                  'production_bin'],
            ['scripts/big_blast.pl',                  'production_bin'],
            ['scripts/sequenceformat.converter.pl',   'production_bin'],
            ['scripts/embl_to_ps.pl',                 'production_bin'],
            ['scripts/rfamscan2tab.pl',               'production_bin'],
            ['scripts/tmhmm2embl.pl',                 'production_bin'],
            ['scripts/psu_union.pl',                  'production_bin'],
            ['scripts/signalp2embl.pl',               'production_bin'],
            ['scripts/rfamscan_chado',                'production_bin'],
            ['scripts/psu_splitter.pl',               'production_bin'],
            ['scripts/split_fa.pl',                   'production_bin'],
            ['scripts/fasta_extractor.pl',            'production_bin'],
            ['scripts/dgpi_chado',                    'production_bin'],
            ['scripts/pfamscan2tab.pl',               'production_bin'],
            ['scripts/annotations_update.pl',         'production_bin'],
            ['scripts/orthomcl_chado',                'production_bin'],
            ['scripts/blast2tab.pl',                  'production_bin'],
            ['scripts/sequence_search.pl',            'production_bin'],
            ['scripts/omcl2genedb.pl',                'production_bin'],
            ['modules/GoogleDocument.pm',             'production_lib'],  
            ['modules/GoogleDocumentHelper.pm',       'production_lib'],
            ['scripts/contigs2fas.pl',                'production_bin'],
            ['scripts/validate_embl.pl',              'production_bin'],
            ['scripts/shuffle_reads',                 'production_bin'],
            ['scripts/assemble_lanes',                'production_bin'],
            ['scripts/map2bam.pl',                    'production_bin'],
	          ['scripts/team133-bsub.pl',               'production_bin'],
            ['modules/Pathfind.pm',                   'production_lib'],
            ['modules/PathfindLog.pm',                'production_lib'],
            ['modules/FindLanes.pm',                  'production_lib'],
            ['modules/SubmissionLookup.pm',           'production_lib'],
            ['scripts/species_frequency',             'production_bin'],
            ['scripts/tradisfind',             	      'production_bin'],
            ['scripts/stats_and_graphs_for_bams',     'pathdev_bin'   ],
	          ['scripts/sh16_scripts_to_git.pl',        'pathdev_bin'   ],
	          ['scripts/jit_scripts_to_git.pl',         'pathdev_bin'   ],
	          ['scripts/fasta_one_line.pl',             'production_bin'],
            ['scripts/list_species_sequenced.pl',     'pathdev_bin'   ],
	          ['scripts/cshrc_to_bash.pl',              'pathdev_bin'   ],
            ['scripts/infofind',                      'production_bin'],
            ['scripts/select_gene_sequences.pl',      'production_bin'],
        ]
  java: [ ["googlecode.jar", "production_java"] ]
  
  c: [[ "bin/assembly_stats", 'production_bin']]
  r: [[ "scripts/tradis_essentiality.R", 'production_bin']]
  
  shell: [
            ['scripts/genus_genbank_to_blast',             'pathdev_bin'   ],
            ['scripts/refseq_blast_databases',             'pathdev_bin'   ],
            ['scripts/update_tracking_databases.sh',       'pathdev_bin'   ],
            ['scripts/wtsi_chado_privs.ksh',               'pathdev_bin'   ],
            ['scripts/load_organisms.sh',                  'pathdev_bin'   ],
            ['scripts/setup_pathpipe_environment.sh',      'pathdev_bin'   ],
            ['scripts/setup_test_pathpipe_environment.sh', 'pathdev_bin'   ],
            ['scripts/concatgff.sh',                       'pathdev_bin'   ],
            ['scripts/tmhmm_chado',                        'production_bin'],
            ['scripts/writedb_entry',                      'production_bin'],
            ['scripts/chado_dump_transcripts',             'production_bin'],
            ['scripts/iprscan_chado',                      'production_bin'],
            ['scripts/art_act_launcher',                   'production_bin'],
            ['scripts/tmhmm_chado',                        'production_bin'],
            ['scripts/pfamscan_chado',                     'production_bin'],
            ['scripts/chado_dump_proteins',                'production_bin'],
            ['scripts/chado_dump_introns',                 'production_bin'],
            ['scripts/iprscan',                            'production_bin'],
            ['scripts/pmid_extraction',                    'production_bin'],
            ['scripts/dnaplotter',                         'production_bin'],
            ['scripts/art',                                'production_bin'],
            ['scripts/act',                                'production_bin'],
            ['scripts/disk_usage_report.sh',               'pathdev_bin'   ],
            ['scripts/directory_size_report.sh',           'pathdev_bin'   ],
            ['scripts/generate_ref_index.sh',              'pathdev_bin'   ],
            ['scripts/orientationtracker.sh',              'production_bin'],
            ['scripts/chado_dump_proteins_ordered',   	   'production_bin'],
            ['scripts/chado_dump_transcripts_coding',      'production_bin'],
            ['scripts/chado_dump_transcripts_rna',         'production_bin'],
	    ['scripts/db_info',         'production_bin'],
	    ['scripts/run_jspecies',         'production_bin']
        ]
  splimer: [['splimer.pl',			'production_bin'],
  	    ['modules/FastaLength.pm',		'production_lib'],
	]
